<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">DuplicateConfiguration</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwluZXdDb25maWd1cmF0aW9uTmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vy
c29yLCAibmV3Q29uZmlndXJhdGlvbk5hbWUiICk7DQpTdHJpbmcJbmV3Q29uZmlndXJhdGlvbkNv
bW1lbnQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgIm5ld0NvbmZpZ3Vy
YXRpb25Db21tZW50IiApOw0KU3RyaW5nCWNvbmZpZ3VyYXRpb24gPSBJRGF0YVV0aWwuZ2V0U3Ry
aW5nKCBwaXBlbGluZUN1cnNvciwgImNvbmZpZ3VyYXRpb24iICk7DQoNCg0KSURhdGFVdGlsLnB1
dChwaXBlbGluZUN1cnNvciwgIm1lc3NhZ2UiLCBtU3VjY2Vzc01zZyArICIoIiArIG5ld0NvbmZp
Z3VyYXRpb25OYW1lKyAiKSIpOw0KdHJ5IHsNCglQcm9wZXJ0aWVzTWFuYWdlci5kdXBsaWNhdGVQ
cm9wZXJ0aWVzKGNvbmZpZ3VyYXRpb24sbmV3Q29uZmlndXJhdGlvbk5hbWUsbmV3Q29uZmlndXJh
dGlvbkNvbW1lbnQpOyANCn0NCmNhdGNoIChFeGNlcHRpb24gZXhjcCkgew0KCUlEYXRhVXRpbC5w
dXQocGlwZWxpbmVDdXJzb3IsICJtZXNzYWdlIiwgbUVycm9yTXNnICsgIigiICsgZXhjcC5nZXRN
ZXNzYWdlKCkgKyAiKSIpOw0KfQ0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KcmVzZXRDYWNo
ZWRTZXJ2aWNlcyhwaXBlbGluZSk7DQoJ</value>
</Values>
